import { Table } from "antd";
import { useTranslation } from "react-i18next";
import { StyledTitle } from "./styles";

const ReportProjectStatus = () => {
  const { t } = useTranslation(["common"]);

  const columns = [
    {
      title: "No.",
      dataIndex: "key",
      key: "key",
      width: 50,
    },
    {
      title: `${t("tableContent.column.code")}`,
      dataIndex: "prjCode",
      key: "prjCode",
    },
    {
      title: `${t("tableContent.column.projectName")}`,
      dataIndex: "prjName",
      key: "prjName",
    },
    {
      title: `${t("tableContent.column.customer")}`,
      dataIndex: "cusName",
      key: "cusName",
    },
    {
      title: `${t("tableContent.column.categoryName")}`,
      dataIndex: "cateName",
      key: "cateName",
    },
    {
      title: `${t("tableContent.column.workType")}`,
      dataIndex: "cateWork",
      key: "cateWork",
    },
    {
      title: `${t("tableContent.column.shipment")}`,
      dataIndex: "shipmentNo",
      key: "shipmentNo",
    },
    {
      title: `${t("tableContent.column.po/contract")}`,
      children: [
        {
          title: `${t("tableContent.column.mass")}`,
          dataIndex: "weight",
          key: "weight",
        },
        {
          title: `${t("tableContent.column.deliveryDate")}`,
          dataIndex: "deliveryDate",
          key: "deliveryDate",
        },
      ],
    },
    {
      title: `${t("tableContent.column.actualContract")}`,
      children: [
        {
          title: `${t("tableContent.column.mass")}`,
          dataIndex: "weightActual",
          key: "weightActual",
        },
        {
          title: `${t("tableContent.column.deliveryDate")}`,
          dataIndex: "deliveryDateActual",
          key: "deliveryDateActual",
        },
      ],
    },
    {
      title: `${t("tableContent.column.poAmountContractValue")}`,
      children: [
        {
          title: "USD",
          dataIndex: "USD",
          key: "USD",
        },
        {
          title: "VND",
          dataIndex: "VND",
          key: "VND",
        },
        {
          title: "EUR",
          dataIndex: "EUR",
          key: "EUR",
        },
      ],
    },
    {
      title: `${t("tableContent.column.poActualAmount")}`,
      children: [
        {
          title: "USD",
          dataIndex: "realUSD",
          key: "realUSD",
        },
        {
          title: "VND",
          dataIndex: "realVND",
          key: "realVND",
        },
        {
          title: "EUR",
          dataIndex: "realEUR",
          key: "realEUR",
        },
      ],
    },
    {
      title: `${t("tableContent.column.poActualAmount")}`,
      dataIndex: "conditionShipment",
      conditionShipment: "key",
    },
    {
      title: `${t("tableContent.column.paymentCondition")}`,
      children: [
        {
          title: `${t("tableContent.column.advance")}`,
          dataIndex: "advance",
          key: "advance",
        },
        {
          title: `${t("tableContent.column.paymentForMaterials")}`,
          dataIndex: "material",
          key: "material",
        },
        {
          title: `${t("tableContent.column.1stPayment")}`,
          dataIndex: "payentFirst",
          key: "payentFirst",
        },
        {
          title: `${t("tableContent.column.2ndPayment")}`,
          dataIndex: "payentSecond",
          key: "payentSecond",
        },
        {
          title: `${t("tableContent.column.3rdPayment")}`,
          dataIndex: "payentThirty",
          key: "payentThirty",
        },
        {
          title: `${t("tableContent.column.finalPayment")}`,
          dataIndex: "payentFinal",
          key: "payentFinal",
        },
        {
          title: `${t("tableContent.column.paymentMethod")}`,
          dataIndex: "methodPayment",
          key: "methodPayment",
        },
        {
          title: `${t("tableContent.column.guaranteeCondition")}`,
          dataIndex: "conditionGuarantee",
          key: "conditionGuarantee",
        },
        {
          title: `${t("tableContent.column.penaltyRate")}`,
          dataIndex: "scalePunish",
          key: "scalePunish",
        },
      ],
    },
    {
      title: `${t("tableContent.column.projectPresident")}`,
      dataIndex: "manager",
      key: "manager",
    },
    {
      title: `${t("tableContent.column.projectManager")}`,
      dataIndex: "manage",
      key: "manage",
    },
    {
      title: `${t("tableContent.column.3DModeling")}`,
      children: [
        {
          title: `${t("tableContent.column.startedDate")}`,
          dataIndex: "start_date_1",
          key: "start_date_1",
        },
        {
          title: `${t("tableContent.column.finishedDate")}`,
          dataIndex: "finished_date_1",
          key: "finished_date_1",
        },
        {
          title: `${t("tableContent.column.weight")}`,
          dataIndex: "weight_1",
          key: "weight_1",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_kg_1",
          key: "plan_kg_1",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_kg_1",
          key: "actual_kg_1",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_1",
          key: "plan_1",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "actual_1",
          key: "actual_1",
        },
      ],
    },
    {
      title: "MPR",
      children: [
        {
          title: `${t("tableContent.column.startedDate")}`,
          dataIndex: "start_date_2",
          key: "start_date_2",
        },
        {
          title: `${t("tableContent.column.finishedDate")}`,
          dataIndex: "finished_date_2",
          key: "finished_date_2",
        },
        {
          title: `${t("tableContent.column.weight")}`,
          dataIndex: "weight_2",
          key: "weight_2",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_kg_2",
          key: "plan_kg_2",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_kg_2",
          key: "actual_kg_2",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_2",
          key: "plan_2",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "actual_2",
          key: "actual_2",
        },
      ],
    },
    {
      title: "Shop Drawing",
      children: [
        {
          title: `${t("tableContent.column.startedDate")}`,
          dataIndex: "start_date_3",
          key: "start_date_3",
        },
        {
          title: `${t("tableContent.column.finishedDate")}`,
          dataIndex: "finished_date_3",
          key: "finished_date_3",
        },
        {
          title: `${t("tableContent.column.weight")}`,
          dataIndex: "weight_3",
          key: "weight_3",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_kg_3",
          key: "plan_kg_3",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_kg_3",
          key: "actual_kg_3",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_3",
          key: "plan_3",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_3",
          key: "actual_3",
        },
      ],
    },
    {
      title: `${t("tableContent.column.cuttingPlan")}`,
      children: [
        {
          title: `${t("tableContent.column.startedDate")}`,
          dataIndex: "start_date_4",
          key: "start_date_4",
        },
        {
          title: `${t("tableContent.column.finishedDate")}`,
          dataIndex: "finished_date_4",
          key: "finished_date_4",
        },
        {
          title: `${t("tableContent.column.weight")}`,
          dataIndex: "weight_4",
          key: "weight_4",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_kg_4",
          key: "plan_kg_4",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_kg_4",
          key: "actual_kg_4",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_4",
          key: "plan_4",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_4",
          key: "actual_4",
        },
      ],
    },
    {
      title: "B.O.M",
      children: [
        {
          title: `${t("tableContent.column.startedDate")}`,
          dataIndex: "start_date_5",
          key: "start_date_5",
        },
        {
          title: `${t("tableContent.column.finishedDate")}`,
          dataIndex: "finished_date_5",
          key: "finished_date_5",
        },
        {
          title: `${t("tableContent.column.weight")}`,
          dataIndex: "weight_5",
          key: "weight_5",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_kg_5",
          key: "plan_kg_5",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_kg_5",
          key: "actual_kg_5",
        },
        {
          title: `${t("tableContent.column.plan")}`,
          dataIndex: "plan_5",
          key: "plan_5",
        },
        {
          title: `${t("tableContent.column.actual")}`,
          dataIndex: "actual_5",
          key: "actual_5",
        },
      ],
    },
  ];

  const data = [];
  data.push({
    key: 1,
    prjCode: "F0122",
    prjName: "BLACKPOINT",
    cusName: "BHI",
    cateName: "	HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "2.127.244",
    deliveryDate: "15-Mar-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "1.100.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "",
    methodPayment: "",
    conditionGuarantee: "",
    scalePunish: "",
    manager: "(Mr. Jeff)",
    manage: "Mr. Anh",
    start_date_1: "0-jan-00",
    finished_date_1: "0-jan-00",
    weight_1: "20%",
    plan_kg_1: "0,0",
    actual_kg_1: "0,0",
    plan_1: "0%",
    actual_1: "0%",
    start_date_2: "0-jan-00",
    finished_date_2: "0-jan-00",
    weight_2: "20%",
    plan_kg_2: "2.127.244,0",
    actual_kg_2: "2.127.244,0",
    plan_2: "0%",
    actual_2: "0%",
    start_date_3: "0-jan-00",
    finished_date_3: "0-jan-00",
    weight_3: "20%",
    plan_kg_3: "2.127.244,0",
    actual_kg_3: "2.127.244,0",
    plan_3: "0%",
    actual_3: "0%",
    start_date_4: "0-jan-00",
    finished_date_4: "0-jan-00",
    weight_4: "20%",
    plan_kg_4: "2.127.244,0",
    actual_kg_4: "2.127.244,0",
    plan_4: "0%",
    actual_4: "0%",
    start_date_5: "0-jan-00",
    finished_date_5: "0-jan-00",
    weight_5: "20%",
    plan_kg_5: "2.127.244,0",
    actual_kg_5: "2.127.244,0",
    plan_5: "0%",
    actual_5: "0%",
  });
  data.push({
    key: 2,
    prjCode: "F0136",
    prjName: "DATAN 7(Taiwan)",
    cusName: "MCI",
    cateName: "	HRSG Secondary Structures",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "545.000",
    deliveryDate: "31-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "1.100.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FOB",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 15 Days L/C 45 Days",
    methodPayment:
      "Advance Payment Bond (10%) Performance Bond (10%) Warranty Bond (10%)",
    conditionGuarantee: "1%",
    scalePunish: "",
    manager: "(Mr. Van)",
    manage: "Mr. Dung",
    start_date_1: "0-jan-00",
    finished_date_1: "0-jan-00",
    weight_1: "20%",
    plan_kg_1: "574.697,0",
    actual_kg_1: "574.697,0",
    plan_1: "0%",
    actual_1: "0%",
    start_date_2: "0-jan-00",
    finished_date_2: "0-jan-00",
    weight_2: "20%",
    plan_kg_2: "574.697,0",
    actual_kg_2: "574.697,0",
    plan_2: "0%",
    actual_2: "0%",
    start_date_3: "0-jan-00",
    finished_date_3: "0-jan-00",
    weight_3: "20%",
    plan_kg_3: "574.697,0",
    actual_kg_3: "574.697,0",
    plan_3: "0%",
    actual_3: "0%",
    start_date_4: "0-jan-00",
    finished_date_4: "0-jan-00",
    weight_4: "20%",
    plan_kg_4: "574.697,0",
    actual_kg_4: "574.697,0",
    plan_4: "0%",
    actual_4: "0%",
    start_date_5: "0-jan-00",
    finished_date_5: "0-jan-00",
    weight_5: "20%",
    plan_kg_5: "574.697,0",
    actual_kg_5: "574.697,0",
    plan_5: "0%",
    actual_5: "0%",
  });
  data.push({
    key: 3,
    prjCode: "F0139",
    prjName: "SARAWAK (Malaysia)",
    cusName: "SECL",
    cateName: "Platform & Ladder",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "193.000",
    deliveryDate: "30-Apr-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "772.878",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "DDP/FOB",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 45 Days",
    methodPayment:
      "Advance Payment Bond (10%)Performance Bond (10%) Warranty Bond (10%)",
    conditionGuarantee: "0.15% per day",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    start_date_1: "0-jan-00",
    finished_date_1: "0-jan-00",
    weight_1: "20%",
    plan_kg_1: "193.000,0",
    actual_kg_1: "193.000,0",
    plan_1: "0%",
    actual_1: "0%",
    start_date_2: "0-jan-00",
    finished_date_2: "0-jan-00",
    weight_2: "20%",
    plan_kg_2: "193.000,0",
    actual_kg_2: "193.000,0",
    plan_2: "0%",
    actual_2: "0%",
    start_date_3: "0-jan-00",
    finished_date_3: "0-jan-00",
    weight_3: "20%",
    plan_kg_3: "193.000,0",
    actual_kg_3: "193.000,0",
    plan_3: "0%",
    actual_3: "0%",
    start_date_4: "0-jan-00",
    finished_date_4: "0-jan-00",
    weight_4: "20%",
    plan_kg_4: "193.000,0",
    actual_kg_4: "193.000,0",
    plan_4: "0%",
    actual_4: "0%",
    start_date_5: "0-jan-00",
    finished_date_5: "0-jan-00",
    weight_5: "20%",
    plan_kg_5: "193.000,0",
    actual_kg_5: "193.000,0",
    plan_5: "0%",
    actual_5: "0%",
  });
  data.push({
    key: 4,
    prjCode: "F0141",
    prjName: "SHURTAN(Uzbekistan)",
    cusName: "JNK",
    cateName: "Fired Heate",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "1.163.116",
    deliveryDate: "31-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "3.350.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FCA Shop",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 30 Days",
    methodPayment: "Advance Payment Bond (10%)",
    conditionGuarantee: "2%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    start_date_1: "0,0",
    finished_date_1: "0,0",
    weight_1: "20%",
    plan_kg_1: "HOLD",
    actual_kg_1: "HOLD",
    plan_1: "HOLD",
    actual_1: "HOLD",
    start_date_2: "0,0",
    finished_date_2: "0,0",
    weight_2: "HOLD",
    plan_kg_2: "HOLD",
    actual_kg_2: "HOLD",
    plan_2: "HOLD",
    actual_2: "HOLD",
    start_date_3: "0,0",
    finished_date_3: "0,0",
    weight_3: "HOLD",
    plan_kg_3: "HOLD",
    actual_kg_3: "HOLD",
    plan_3: "HOLD",
    actual_3: "HOLD",
    start_date_4: "0,0",
    finished_date_4: "0,0",
    weight_4: "HOLD",
    plan_kg_4: "HOLD",
    actual_kg_4: "HOLD",
    plan_4: "HOLD",
    actual_4: "HOLD",
    start_date_5: "0,0",
    finished_date_5: "0,0",
    weight_5: "HOLD",
    plan_kg_5: "HOLD",
    actual_kg_5: "HOLD",
    plan_5: "HOLD",
    actual_5: "HOLD",
  });
  data.push({
    key: 5,
    prjCode: "F0143",
    prjName: "BATANGAS (Philippines)",
    cusName: "VOGT POWER",
    cateName: "HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "3.405.783",
    deliveryDate: "09-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "6.900.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 60 Days",
    methodPayment: "Advance Payment Bond (10%)Warranty Bond (10%)",
    conditionGuarantee: "1st Week = 3% 2nd Week = 5% >3rd Week = 10%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    start_date_1: "0-jan-00",
    finished_date_1: "0-jan-00",
    weight_1: "20%",
    plan_kg_1: "193.000,0",
    actual_kg_1: "193.000,0",
    plan_1: "0%",
    actual_1: "0%",
    start_date_2: "0-jan-00",
    finished_date_2: "0-jan-00",
    weight_2: "20%",
    plan_kg_2: "193.000,0",
    actual_kg_2: "193.000,0",
    plan_2: "0%",
    actual_2: "0%",
    start_date_3: "0-jan-00",
    finished_date_3: "0-jan-00",
    weight_3: "20%",
    plan_kg_3: "193.000,0",
    actual_kg_3: "193.000,0",
    plan_3: "0%",
    actual_3: "0%",
    start_date_4: "0-jan-00",
    finished_date_4: "0-jan-00",
    weight_4: "20%",
    plan_kg_4: "193.000,0",
    actual_kg_4: "193.000,0",
    plan_4: "0%",
    actual_4: "0%",
    start_date_5: "0-jan-00",
    finished_date_5: "0-jan-00",
    weight_5: "20%",
    plan_kg_5: "193.000,0",
    actual_kg_5: "193.000,0",
    plan_5: "0%",
    actual_5: "0%",
  });
  data.push({
    key: 6,
    prjCode: "F0144",
    prjName: "BATANGAS (Philippines)",
    cusName: "VOGT POWER",
    cateName: "HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "3.405.783",
    deliveryDate: "09-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "6.900.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 60 Days",
    methodPayment: "Advance Payment Bond (10%)Warranty Bond (10%)",
    conditionGuarantee: "1st Week = 3% 2nd Week = 5% >3rd Week = 10%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    start_date_1: "DONE",
    finished_date_1: "DONE",
    weight_1: "20%",
    plan_kg_1: "3.457.100,0",
    actual_kg_1: "3.457.100,0",
    plan_1: "",
    actual_1: "",
    start_date_2: "DONE",
    finished_date_2: "DONE",
    weight_2: "20%",
    plan_kg_2: "3.457.100,0",
    actual_kg_2: "3.457.100,0",
    plan_2: "",
    actual_2: "",
    start_date_3: "DONE",
    finished_date_3: "DONE",
    weight_3: "20%",
    plan_kg_3: "3.457.100,0",
    actual_kg_3: "3.457.100,0",
    plan_3: "",
    actual_3: "",
    start_date_4: "DONE",
    finished_date_4: "DONE",
    weight_4: "20%",
    plan_kg_4: "3.457.100,0",
    actual_kg_4: "3.457.100,0",
    plan_4: "",
    actual_4: "",
    start_date_5: "DONE",
    finished_date_5: "DONE",
    weight_5: "20%",
    plan_kg_5: "3.457.100,0",
    actual_kg_5: "3.457.100,0",
    plan_5: "",
    actual_5: "",
  });
  data.push({
    key: 7,
    prjCode: "F0145",
    prjName: "BATANGAS (Philippines)",
    cusName: "VOGT POWER",
    cateName: "HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "3.405.783",
    deliveryDate: "09-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "6.900.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 60 Days",
    methodPayment: "Advance Payment Bond (10%)Warranty Bond (10%)",
    conditionGuarantee: "1st Week = 3% 2nd Week = 5% >3rd Week = 10%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    start_date_1: "0-jan-00",
    finished_date_1: "0-jan-00",
    weight_1: "20%",
    plan_kg_1: "193.000,0",
    actual_kg_1: "193.000,0",
    plan_1: "0%",
    actual_1: "0%",
    start_date_2: "0-jan-00",
    finished_date_2: "0-jan-00",
    weight_2: "20%",
    plan_kg_2: "193.000,0",
    actual_kg_2: "193.000,0",
    plan_2: "0%",
    actual_2: "0%",
    start_date_3: "0-jan-00",
    finished_date_3: "0-jan-00",
    weight_3: "20%",
    plan_kg_3: "193.000,0",
    actual_kg_3: "193.000,0",
    plan_3: "0%",
    actual_3: "0%",
    start_date_4: "0-jan-00",
    finished_date_4: "0-jan-00",
    weight_4: "20%",
    plan_kg_4: "193.000,0",
    actual_kg_4: "193.000,0",
    plan_4: "0%",
    actual_4: "0%",
    start_date_5: "0-jan-00",
    finished_date_5: "0-jan-00",
    weight_5: "20%",
    plan_kg_5: "193.000,0",
    actual_kg_5: "193.000,0",
    plan_5: "0%",
    actual_5: "0%",
  });

  return (
    <div>
      <StyledTitle>Project infomation</StyledTitle>
      <Table
        columns={columns}
        dataSource={data}
        bordered={true}
        size="middle"
        scroll={{ x: "calc(10000px + 50%)", y: "100%" }}
      />
    </div>
  );
};

export default ReportProjectStatus;
