import React from 'react';
import { Table } from 'antd';
import { ColumnsType } from 'antd/es/table';
import { StyledTitle } from "./styles";

interface DataType {
    key: React.Key;
    name: string;
    age: number;
    street: string;
    building: string;
    number: number;
    companyAddress: string;
    companyName: string;
    gender: string;
}
      
const columns: ColumnsType<DataType> = [
    {
        title: 'No.',
        dataIndex: 'key',
        key: 'key',
        width: 50
    },
    {
        title: 'Số dự án',
        dataIndex: 'prjCode',
        key: 'prjCode',
    },
    {
        title: 'Tên dự án',
        dataIndex: 'prjName',
        key: 'prjName',
    },
    {
        title: 'Tên khách hàng',
        dataIndex: 'cusName',
        key: 'cusName',
    },
    {
        title: 'Tên hạng mục',
        dataIndex: 'cateName',
        key: 'cateName',
    },
    {
        title: 'Loại công việc',
        dataIndex: 'cateWork',
        key: 'cateWork',
    },
    {
        title: 'Chuyến hàng số',
        dataIndex: 'shipmentNo',
        key: 'shipmentNo',
    },
    {
        title: 'PO/Hợp đồng',
        children: [
            {
                title: 'Khối lượng',
                dataIndex: 'weight',
                key: 'weight',
            },
            {
                title: 'Ngày giao hàng',
                dataIndex: 'deliveryDate',
                key: 'deliveryDate',
            },
        ]
    },
    {
        title: 'Actual/ Thực tế hợp đồng',
        children: [
            {
                title: 'Khối lượng',
                dataIndex: 'weightActual',
                key: 'weightActual',
            },
            {
                title: 'Ngày giao hàng',
                dataIndex: 'deliveryDateActual',
                key: 'deliveryDateActual',
            },
        ]
    },
    {
        title: 'PO Amount/ Giá trị hợp đồng',
        children: [
            {
                title: 'USD',
                dataIndex: 'USD',
                key: 'USD',
            },
            {
                title: 'VND',
                dataIndex: 'VND',
                key: 'VND',
            },
            {
                title: 'EUR',
                dataIndex: 'EUR',
                key: 'EUR',
            },
        ]
    },
    {
        title: 'PO Amount/ Giá trị thực tế',
        children: [
            {
                title: 'USD',
                dataIndex: 'realUSD',
                key: 'realUSD',
            },
            {
                title: 'VND',
                dataIndex: 'realVND',
                key: 'realVND',
            },
            {
                title: 'EUR',
                dataIndex: 'realEUR',
                key: 'realEUR',
            },
        ]
    },
    {
        title: 'Điều kiện giao hàng',
        dataIndex: 'conditionShipment',
        conditionShipment: 'key',
    },
    {
        title: 'Payment Condition/ Điều kiện thanh toán',
        children: [
            {
                title: 'Tạm ứng',
                dataIndex: 'advance',
                key: 'advance',
            },
            {
                title: 'Thanh toán tiền vật tư',
                dataIndex: 'material',
                key: 'material',
            },
            {
                title: '1st payment/ Lần 1',
                dataIndex: 'payentFirst',
                key: 'payentFirst',
            },
            {
                title: '2st payment/ Lần 2',
                dataIndex: 'payentSecond',
                key: 'payentSecond',
            },
            {
                title: '3st payment/ Lần 3',
                dataIndex: 'payentThirty',
                key: 'payentThirty',
            },
            {
                title: 'Final payment/ Lần cuối',
                dataIndex: 'payentFinal',
                key: 'payentFinal',
            },
            {
                title: 'Phương thức thanh toán',
                dataIndex: 'methodPayment',
                key: 'methodPayment',
            },
            {
                title: 'Điều kiện bảo lãnh',
                dataIndex: 'conditionGuarantee',
                key: 'conditionGuarantee',
            },
            {
                title: 'Tỉ lệ phạt',
                dataIndex: 'scalePunish',
                key: 'scalePunish',
            },
        ]
    },
    {
        title: 'Giám đốc dự án',
        dataIndex: 'manager',
        key: 'manager',
    },
    {
        title: 'Quản lý dự án',
        dataIndex: 'manage',
        key: 'manage',
    },
    {
        title: 'Cutting',
        children: [
            {
                title: 'Start date',
                dataIndex: 'start_date_1',
                key: 'start_date_1',
            },
            {
                title: 'Finished Date',
                dataIndex: 'finished_date_1',
                key: 'finished_date_1',
            },
            {
                title: 'Weight',
                dataIndex: 'weight_1',
                key: 'weight_1',
            },
            {
                title: 'Plan(kg)',
                dataIndex: 'plan_kg_1',
                key: 'plan_kg_1',
            },
            {
                title: 'Actual(kg)',
                dataIndex: 'actual_kg_1',
                key: 'actual_kg_1',
            },
            {
                title: 'Plan(%)',
                dataIndex: 'plan_1',
                key: 'plan_1',
            },
            {
                title: 'Actual(%)',
                dataIndex: 'actual_1',
                key: 'actual_1',
            },
        ]
    },
    {
        title: 'Fabrication',
        children: [
            {
                title: 'Start date',
                dataIndex: 'start_date_2',
                key: 'start_date_2',
            },
            {
                title: 'Finished Date',
                dataIndex: 'finished_date_2',
                key: 'finished_date_2',
            },
            {
                title: 'Weight',
                dataIndex: 'weight_2',
                key: 'weight_2',
            },
            {
                title: 'Plan(kg)',
                dataIndex: 'plan_kg_2',
                key: 'plan_kg_2',
            },
            {
                title: 'Actual(kg)',
                dataIndex: 'actual_kg_2',
                key: 'actual_kg_2',
            },
            {
                title: 'Plan(%)',
                dataIndex: 'plan_2',
                key: 'plan_2',
            },
            {
                title: 'Actual(%)',
                dataIndex: 'actual_2',
                key: 'actual_2',
            },
        ]
    },
    {
        title: 'Insulation',
        children: [
            {
                title: 'Start date',
                dataIndex: 'start_date_3',
                key: 'start_date_3',
            },
            {
                title: 'Finished Date',
                dataIndex: 'finished_date_3',
                key: 'finished_date_3',
            },
            {
                title: 'Weight',
                dataIndex: 'weight_3',
                key: 'weight_3',
            },
            {
                title: 'Plan(kg)',
                dataIndex: 'plan_kg_3',
                key: 'plan_kg_3',
            },
            {
                title: 'Actual(kg)',
                dataIndex: 'actual_kg_3',
                key: 'actual_kg_3',
            },
            {
                title: 'Plan(%)',
                dataIndex: 'plan_3',
                key: 'plan_3',
            },
            {
                title: 'Actual(%)',
                dataIndex: 'actual_3',
                key: 'actual_3',
            },
        ]
    },
    {
        title: 'Painting',
        children: [
            {
                title: 'Start date',
                dataIndex: 'start_date_4',
                key: 'start_date_4',
            },
            {
                title: 'Finished Date',
                dataIndex: 'finished_date_4',
                key: 'finished_date_4',
            },
            {
                title: 'Weight',
                dataIndex: 'weight_4',
                key: 'weight_4',
            },
            {
                title: 'Plan(kg)',
                dataIndex: 'plan_kg_4',
                key: 'plan_kg_4',
            },
            {
                title: 'Actual(kg)',
                dataIndex: 'actual_kg_4',
                key: 'actual_kg_4',
            },
            {
                title: 'Plan(%)',
                dataIndex: 'plan_4',
                key: 'plan_4',
            },
            {
                title: 'Actual(%)',
                dataIndex: 'actual_4',
                key: 'actual_4',
            },
        ]
    },
    {
        title: 'Packing',
        children: [
            {
                title: 'Start date',
                dataIndex: 'start_date_5',
                key: 'start_date_5',
            },
            {
                title: 'Finished Date',
                dataIndex: 'finished_date_5',
                key: 'finished_date_5',
            },
            {
                title: 'Weight',
                dataIndex: 'weight_5',
                key: 'weight_5',
            },
            {
                title: 'Plan(kg)',
                dataIndex: 'plan_kg_5',
                key: 'plan_kg_5',
            },
            {
                title: 'Actual(kg)',
                dataIndex: 'actual_kg_5',
                key: 'actual_kg_5',
            },
            {
                title: 'Plan(%)',
                dataIndex: 'plan_5',
                key: 'plan_5',
            },
            {
                title: 'Actual(%)',
                dataIndex: 'actual_5',
                key: 'actual_5',
            },
        ]
    },
];
      
const data: DataType[] = [];

data.push({
    key: 1,
    prjCode: 'F0122',
    prjName: 'BLACKPOINT',
    cusName: 'BHI',
    cateName: '	HRSG Non-Pressure Parts',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '2.127.244',
    deliveryDate: '15-Mar-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '1.100.000',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'FAS',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: '',
    methodPayment: '',
    conditionGuarantee: '',
    scalePunish: '',
    manager: '(Mr. Jeff)',
    manage: 'Mr. Anh',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});
data.push({
    key: 2,
    prjCode: 'F0136',
    prjName: 'DATAN 7(Taiwan)',
    cusName: 'MCI',
    cateName: '	HRSG Secondary Structures',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '545.000',
    deliveryDate: '31-Jan-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '1.100.000',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'FOB',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: 'T/T 15 Days L/C 45 Days',
    methodPayment: 'Advance Payment Bond (10%) Performance Bond (10%) Warranty Bond (10%)',
    conditionGuarantee: '1%',
    scalePunish: '',
    manager: '(Mr. Van)',
    manage: 'Mr. Dung',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});
data.push({
    key: 3,
    prjCode: 'F0139',
    prjName: 'SARAWAK (Malaysia)',
    cusName: 'SECL',
    cateName: 'Platform & Ladder',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '193.000',
    deliveryDate: '30-Apr-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '772.878',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'DDP/FOB',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: 'T/T 45 Days',
    methodPayment: 'Advance Payment Bond (10%)Performance Bond (10%) Warranty Bond (10%)',
    conditionGuarantee: '0.15% per day',
    scalePunish: '',
    manager: '(Mr. Dinh)',
    manage: 'Mr. The',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});
data.push({
    key: 4,
    prjCode: 'F0141',
    prjName: 'SHURTAN(Uzbekistan)',
    cusName: 'JNK',
    cateName: 'Fired Heate',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '1.163.116',
    deliveryDate: '31-Jan-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '3.350.000',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'FCA Shop',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: 'T/T 30 Days',
    methodPayment: 'Advance Payment Bond (10%)',
    conditionGuarantee: '2%',
    scalePunish: '',
    manager: '(Mr. Dinh)',
    manage: 'Mr. The',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});
data.push({
    key: 5,
    prjCode: 'F0143',
    prjName: 'BATANGAS (Philippines)',
    cusName: 'VOGT POWER',
    cateName: 'HRSG Non-Pressure Parts',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '3.405.783',
    deliveryDate: '09-Jan-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '6.900.000',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'FAS',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: 'T/T 60 Days',
    methodPayment: 'Advance Payment Bond (10%)Warranty Bond (10%)',
    conditionGuarantee: '1st Week = 3% 2nd Week = 5% >3rd Week = 10%',
    scalePunish: '',
    manager: '(Mr. Dinh)',
    manage: 'Mr. The',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});
data.push({
    key: 6,
    prjCode: 'F0144',
    prjName: 'BATANGAS (Philippines)',
    cusName: 'VOGT POWER',
    cateName: 'HRSG Non-Pressure Parts',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '3.405.783',
    deliveryDate: '09-Jan-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '6.900.000',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'FAS',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: 'T/T 60 Days',
    methodPayment: 'Advance Payment Bond (10%)Warranty Bond (10%)',
    conditionGuarantee: '1st Week = 3% 2nd Week = 5% >3rd Week = 10%',
    scalePunish: '',
    manager: '(Mr. Dinh)',
    manage: 'Mr. The',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});

data.push({
    key: 7,
    prjCode: 'F0145',
    prjName: 'BATANGAS (Philippines)',
    cusName: 'VOGT POWER',
    cateName: 'HRSG Non-Pressure Parts',
    cateWork: 'Fab',
    shipmentNo: '',
    weight: '3.405.783',
    deliveryDate: '09-Jan-2022',
    weightActual: '',
    deliveryDateActual: '',
    USD: '6.900.000',
    VND: '',
    EUR: '',
    realUSD: '',
    realVND: '',
    realEUR: '',
    conditionShipment: 'FAS',
    advance: '',
    material: '',
    payentFirst: '',
    payentSecond: '',
    payentThirty: '',
    payentFinal: 'T/T 60 Days',
    methodPayment: 'Advance Payment Bond (10%)Warranty Bond (10%)',
    conditionGuarantee: '1st Week = 3% 2nd Week = 5% >3rd Week = 10%',
    scalePunish: '',
    manager: '(Mr. Dinh)',
    manage: 'Mr. The',
    start_date_1: '',
    finished_date_1: '',
    weight_1: '',
    plan_kg_1: '',
    actual_kg_1: '',
    plan_1: '',
    actual_1: '',
    start_date_2: '',
    finished_date_2: '',
    weight_2: '',
    plan_kg_2: '',
    actual_kg_2: '',
    plan_2: '',
    actual_2: '',
    start_date_3: '',
    finished_date_3: '',
    weight_3: '',
    plan_kg_3: '',
    actual_kg_3: '',
    plan_3: '',
    actual_3: '',
    start_date_4: '',
    finished_date_4: '',
    weight_4: '',
    plan_kg_4: '',
    actual_kg_4: '',
    plan_4: '',
    actual_4: '',
    start_date_5: '',
    finished_date_5: '',
    weight_5: '',
    plan_kg_5: '',
    actual_kg_5: '',
    plan_5: '',
    actual_5: '',
});
const ReportProjectStatus = () => {
  return (
        <div>
           <StyledTitle>Progress Of PDM</StyledTitle>
            <Table
                columns={columns}
                dataSource={data}
                bordered={true}
                size="middle"
                scroll={{ x: 'calc(5500px + 50%)', y: '100%' }}
            />
        </div>
    );
};

export default ReportProjectStatus;
