import { Table } from "antd";
import { useTranslation } from "react-i18next";
import { StyledTitle } from "./styles";

const ReportProjectStatus = () => {
  const { t } = useTranslation(["reportScreen"]);

  const columns = [
    {
      title: "No.",
      dataIndex: "key",
      key: "key",
      width: 50,
    },
    {
      title: "Số dự án",
      dataIndex: "prjCode",
      key: "prjCode",
    },
    {
      title: "Tên dự án",
      dataIndex: "prjName",
      key: "prjName",
    },
    {
      title: "Tên khách hàng",
      dataIndex: "cusName",
      key: "cusName",
    },
    {
      title: "Tên hạng mục",
      dataIndex: "cateName",
      key: "cateName",
    },
    {
      title: "Loại công việc",
      dataIndex: "cateWork",
      key: "cateWork",
    },
    {
      title: "Chuyến hàng số",
      dataIndex: "shipmentNo",
      key: "shipmentNo",
    },
    {
      title: "PO/Hợp đồng",
      children: [
        {
          title: "Khối lượng",
          dataIndex: "weight",
          key: "weight",
        },
        {
          title: "Ngày giao hàng",
          dataIndex: "deliveryDate",
          key: "deliveryDate",
        },
      ],
    },
    {
      title: "Actual/ Thực tế hợp đồng",
      children: [
        {
          title: "Khối lượng",
          dataIndex: "weightActual",
          key: "weightActual",
        },
        {
          title: "Ngày giao hàng",
          dataIndex: "deliveryDateActual",
          key: "deliveryDateActual",
        },
      ],
    },
    {
      title: "PO Amount/ Giá trị hợp đồng",
      children: [
        {
          title: "USD",
          dataIndex: "USD",
          key: "USD",
        },
        {
          title: "VND",
          dataIndex: "VND",
          key: "VND",
        },
        {
          title: "EUR",
          dataIndex: "EUR",
          key: "EUR",
        },
      ],
    },
    {
      title: "PO Amount/ Giá trị thực tế",
      children: [
        {
          title: "USD",
          dataIndex: "realUSD",
          key: "realUSD",
        },
        {
          title: "VND",
          dataIndex: "realVND",
          key: "realVND",
        },
        {
          title: "EUR",
          dataIndex: "realEUR",
          key: "realEUR",
        },
      ],
    },
    {
      title: "Điều kiện giao hàng",
      dataIndex: "conditionShipment",
      conditionShipment: "key",
    },
    {
      title: "Payment Condition/ Điều kiện thanh toán",
      children: [
        {
          title: "Tạm ứng",
          dataIndex: "advance",
          key: "advance",
        },
        {
          title: "Thanh toán tiền vật tư",
          dataIndex: "material",
          key: "material",
        },
        {
          title: "1st payment/ Lần 1",
          dataIndex: "payentFirst",
          key: "payentFirst",
        },
        {
          title: "2st payment/ Lần 2",
          dataIndex: "payentSecond",
          key: "payentSecond",
        },
        {
          title: "3st payment/ Lần 3",
          dataIndex: "payentThirty",
          key: "payentThirty",
        },
        {
          title: "Final payment/ Lần cuối",
          dataIndex: "payentFinal",
          key: "payentFinal",
        },
        {
          title: "Phương thức thanh toán",
          dataIndex: "methodPayment",
          key: "methodPayment",
        },
        {
          title: "Điều kiện bảo lãnh",
          dataIndex: "conditionGuarantee",
          key: "conditionGuarantee",
        },
        {
          title: "Tỉ lệ phạt",
          dataIndex: "scalePunish",
          key: "scalePunish",
        },
      ],
    },
    {
      title: "Giám đốc dự án",
      dataIndex: "manager",
      key: "manager",
    },
    {
      title: "Quản lý dự án",
      dataIndex: "manage",
      key: "manage",
    },
    {
      title: "Progress Of PLD",
      children: [
        {
          title: "Weight",
          dataIndex: "weightPld",
          key: "weightPld",
        },
        {
          title: "Plan(kg)",
          dataIndex: "plan_kg",
          key: "plan_kg",
        },
        {
          title: "Actual(kg)",
          dataIndex: "actual_kg",
          key: "actual_kg",
        },
        {
          title: "Plan(%)",
          dataIndex: "plan",
          key: "plan",
        },
        {
          title: "Actual(%)",
          dataIndex: "actual",
          key: "actual",
        },
      ],
    },
  ];

  const data = [];

  data.push({
    key: 1,
    prjCode: "F0122",
    prjName: "BLACKPOINT",
    cusName: "BHI",
    cateName: "	HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "2.127.244",
    deliveryDate: "15-Mar-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "1.100.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "",
    methodPayment: "",
    conditionGuarantee: "",
    scalePunish: "",
    manager: "(Mr. Jeff)",
    manage: "Mr. Anh",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });
  data.push({
    key: 2,
    prjCode: "F0136",
    prjName: "DATAN 7(Taiwan)",
    cusName: "MCI",
    cateName: "	HRSG Secondary Structures",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "545.000",
    deliveryDate: "31-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "1.100.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FOB",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 15 Days L/C 45 Days",
    methodPayment:
      "Advance Payment Bond (10%) Performance Bond (10%) Warranty Bond (10%)",
    conditionGuarantee: "1%",
    scalePunish: "",
    manager: "(Mr. Van)",
    manage: "Mr. Dung",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });
  data.push({
    key: 3,
    prjCode: "F0139",
    prjName: "SARAWAK (Malaysia)",
    cusName: "SECL",
    cateName: "Platform & Ladder",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "193.000",
    deliveryDate: "30-Apr-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "772.878",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "DDP/FOB",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 45 Days",
    methodPayment:
      "Advance Payment Bond (10%)Performance Bond (10%) Warranty Bond (10%)",
    conditionGuarantee: "0.15% per day",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });
  data.push({
    key: 4,
    prjCode: "F0141",
    prjName: "SHURTAN(Uzbekistan)",
    cusName: "JNK",
    cateName: "Fired Heate",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "1.163.116",
    deliveryDate: "31-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "3.350.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FCA Shop",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 30 Days",
    methodPayment: "Advance Payment Bond (10%)",
    conditionGuarantee: "2%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });
  data.push({
    key: 5,
    prjCode: "F0143",
    prjName: "BATANGAS (Philippines)",
    cusName: "VOGT POWER",
    cateName: "HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "3.405.783",
    deliveryDate: "09-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "6.900.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 60 Days",
    methodPayment: "Advance Payment Bond (10%)Warranty Bond (10%)",
    conditionGuarantee: "1st Week = 3% 2nd Week = 5% >3rd Week = 10%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });
  data.push({
    key: 6,
    prjCode: "F0144",
    prjName: "BATANGAS (Philippines)",
    cusName: "VOGT POWER",
    cateName: "HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "3.405.783",
    deliveryDate: "09-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "6.900.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 60 Days",
    methodPayment: "Advance Payment Bond (10%)Warranty Bond (10%)",
    conditionGuarantee: "1st Week = 3% 2nd Week = 5% >3rd Week = 10%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });

  data.push({
    key: 7,
    prjCode: "F0145",
    prjName: "BATANGAS (Philippines)",
    cusName: "VOGT POWER",
    cateName: "HRSG Non-Pressure Parts",
    cateWork: "Fab",
    shipmentNo: "",
    weight: "3.405.783",
    deliveryDate: "09-Jan-2022",
    weightActual: "",
    deliveryDateActual: "",
    USD: "6.900.000",
    VND: "",
    EUR: "",
    realUSD: "",
    realVND: "",
    realEUR: "",
    conditionShipment: "FAS",
    advance: "",
    material: "",
    payentFirst: "",
    payentSecond: "",
    payentThirty: "",
    payentFinal: "T/T 60 Days",
    methodPayment: "Advance Payment Bond (10%)Warranty Bond (10%)",
    conditionGuarantee: "1st Week = 3% 2nd Week = 5% >3rd Week = 10%",
    scalePunish: "",
    manager: "(Mr. Dinh)",
    manage: "Mr. The",
    weightPld: "",
    plan_kg: "",
    actual_kg: "",
    plan: "",
    actual: "",
  });

  return (
    <div>
      <StyledTitle>Project infomation</StyledTitle>
      <Table
        columns={columns}
        dataSource={data}
        bordered={true}
        size="middle"
        scroll={{ x: "calc(5500px + 50%)", y: "100%" }}
      />
    </div>
  );
};

export default ReportProjectStatus;
